import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { DrawerProvider } from "@/contexts/drawer-context";
import { RoutesProvider } from "@/contexts/routes-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <DrawerProvider>
            <RoutesProvider>
              <AppSidebar />
              <div className="flex flex-col flex-1">
                <header className="flex h-12 shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear">
                  <div className="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6">
                    <SidebarTrigger className="-ml-1 size-12 [&>svg]:size-full" />
                  </div>
                </header>
                <main className="flex-1">
                  {children}
                </main>
              </div>
            </RoutesProvider>
          </DrawerProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
